name: temporal_test
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: docker dependencies
        run: |
          docker network create temporal-network;
          docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions;
          docker compose -f docker-compose.yml up --detach;

      - name: Check Docker Version
        run: |
          go install github.com/grpc-ecosystem/grpc-health-probe@v0.4.15;
          $HOME/go/bin/grpc-health-probe -v -rpc-timeout=10s -addr=localhost:7233 -service=temporal.api.workflowservice.v1.WorkflowService;
